### PR TITLE
Support multiple audiences

### PR DESCRIPTION
**Pull request by felipebn**
Introducing support for multiple audiences for the same authentication domain.

This supports the use case of serving the same Atlassian product instance under two or more domains.

- Existing configuration is migrated automatically, no need for users to do anything.
- Rollback to a previous version is supported out of the box

Configuration UI Changes:
| Before             |  Now |
:-------------------------:|:-------------------------:
image  |  image

### CODE REVIEW

**Comment by t0rrant** [comment]
What happens to the single AUD configured in the current version after an upgrade to this version?

**Review by t0rrant — DISMISSED** [review]
What happens to the single AUD configured in the current version after an upgrade to this version? Does the `base-plugin/src/main/java/com/cloudflare/access/atlassian/base/config/migration/AOMigrationTask0001.java` take care of this?

Other than that LGTM

edit: I noticed you mention this is supported in the description above

**Comment by t0rrant** [comment]
Maybe we should merge #73 first to have tests show up here

**Comment by felipebn** [comment]
> Maybe we should merge #73 first to have tests show up here

Yes that would be the best! As soon the other has another ✅ I'll merge and do a rebase.

**Comment by felipebn** [comment]
Rebased after #73 PR was merged to run include test execution on this PR. Thanks @t0rrant @larcher ! :bowing_man:

**Review by t0rrant — APPROVED** [review]

**Review by larcher — APPROVED** [review]

**Pull request merged**
